// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"biz-hub-auth-service/internal/entity"
	"biz-hub-auth-service/internal/infra/database"
	"biz-hub-auth-service/internal/infra/web"
	"biz-hub-auth-service/internal/usecase"
	"database/sql"
	"github.com/google/wire"
	"github.com/rabbitmq/amqp091-go"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func NewCreateUserUseCase(db *sql.DB) *usecase.CreateUserUseCase {
	userRepository := database.NewUserRepository(db)
	createUserUseCase := usecase.NewCreateUserUseCase(userRepository)
	return createUserUseCase
}

func NewFindUserByEmailUseCase(db *sql.DB) *usecase.FindUserByEmailUseCase {
	userRepository := database.NewUserRepository(db)
	findUserByEmailUseCase := usecase.NewFindUserByEmailUseCase(userRepository)
	return findUserByEmailUseCase
}

func NewWebUserHandler(db *sql.DB, rabbit *amqp091.Connection) *web.WebUserHandler {
	userRepository := database.NewUserRepository(db)
	webUserHandler := web.NewWebUserHandler(userRepository, rabbit)
	return webUserHandler
}

// wire.go:

var setUserRepositoryDependency = wire.NewSet(database.NewUserRepository, wire.Bind(new(entity.UserRepositoryInterface), new(*database.UserRepository)))
